# Generated by Django 3.2.16 on 2022-10-05 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tr_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='interest',
            old_name='test',
            new_name='text',
        ),
    ]
