# Generated by Django 3.2.16 on 2022-10-10 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tr_app', '0005_auto_20221010_1428'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'verbose_name_plural': 'cities'},
        ),
        migrations.RenameField(
            model_name='attraction',
            old_name='interest',
            new_name='city',
        ),
    ]
