# Generated by Django 3.2.16 on 2022-11-16 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tr_app', '0007_city_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='photo',
            field=models.ImageField(default='yet to be uploaded', upload_to='images/'),
            preserve_default=False,
        ),
    ]
