# Generated by Django 3.2.16 on 2022-11-16 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tr_app', '0009_attraction_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='country',
            field=models.CharField(default='uk', max_length=200),
            preserve_default=False,
        ),
    ]
