# Generated by Django 3.2.16 on 2022-11-24 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tr_app', '0011_alter_city_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attraction',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='city',
            name='photo',
        ),
    ]
